name: FortuneEconomyVault
main: com.epherical.fortune.FortunePlugin
version: 1.0.0
author: Thonk
description: Database/Flatfile economy implementation for single/proxy based servers.
api-version: "1.16"
depend: [Vault]
